def __init__(self):
    pass
id_to_caption = {
    12: 'German shepherd, German shepherd dog, German police dog, alsatian', 
    39: 'Egyptian cat', 
    11: 'lycaenid, lycaenid butterfly', 
    0: 'sorrel', 
    21: 'capuchin, ringtail, Cebus capucinus', 
    35: 'African elephant, Loxodonta africana', 
    8: 'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca', 
    3: 'anemone fish', 
    36: 'airliner', 
    18: 'broom', 
    10: 'canoe', 
    15: 'cellular telephone, cellular phone, cellphone, cell, mobile phone', 
    5: 'coffee mug', 
    24: 'convertible', 
    17: 'desktop computer', 
    34: 'digital watch', 
    28: 'electric guitar', 
    37: 'electric locomotive', 
    4: 'espresso maker', 
    25: 'folding chair', 
    16: 'golf ball', 
    30: 'grand piano, grand', 
    2: 'iron, smoothing iron', 
    14: "jack-o'-lantern", 
    23: 'mailbag, postbag', 
    20: 'missile', 
    27: 'mitten', 
    6: 'mountain bike, all-terrain bike, off-roader', 
    31: 'mountain tent', 
    26: "pajama, pyjama, pj's, jammies", 
    1: 'parachute, chute', 
    22: 'pool table, billiard table, snooker table', 
    38: 'radio telescope, radio reflector', 
    29: 'reflex camera', 
    7: 'revolver, six-gun, six-shooter', 
    13: 'running shoe', 
    32: 'banana', 
    19: 'pizza, pizza pie',
    9: 'daisy', 
    33: 'bolete'
}
